### ISSUE TITLE
Ollama base_url

### ISSUE THREAD

**Issue by gavinblair** [sentient-engineering/sentient#12]
My Ollama runs on a different machine on my network. Is there a way to set the base url?

**Comment by nischalj10** [comment]
Hey @gavinblair @myrulezzz - there isn't a support for that yet, but I will add that soon. meanwhile - you can go to the `sentient/utils/providers.py` in the package and chage the base url in the Ollama provider class.

```
class OllamaProvider(LLMProvider):
    def get_client_config(self) -> Dict[str, str]:
        return {
            "api_key": "ollama",
            "base_url": "your_api_url",
        }
```

**Comment by nischalj10** [comment]
@gavinblair @myrulezzz - there's now a way to use a custom open ai compatible server. checkout the [README](https://github.com/sentient-engineering/sentient/blob/main/README.md)
