### ISSUE TITLE
Lmstudio support

### ISSUE THREAD

**Issue by SuperLotar** [sentient-engineering/sentient#25]
Please add support for working with local Lm studio server.

**Comment by nischalj10** [comment]
hey @SuperLotar - you can use LM Studio now! 

I have added compatibility for any open ai compatible server. you can use the custom LLM provider it to set a custom base url and point that to your LM studio server. 

checkout the [README](https://github.com/sentient-engineering/sentient/blob/main/README.md) & [cookbook](https://github.com/sentient-engineering/sentient/blob/main/cookbook.py) for an example
