### ISSUE TITLE
ModuleNotFoundError: No module named 'dotenv'

### ISSUE THREAD

**Issue by utof** [sentient-engineering/sentient#9]
What i did:
1. create new clean python venv
2. pip install sentient
3. run the example code in the README.md

this is the error i get. 

I know the solution: `pip install python-dotenv` just wanna let you know that there's this issue

**Comment by PrajwalPrashanth** [comment]
Ohh yeah. I faced same and installed it manually. @nischalj10

**Comment by nischalj10** [comment]
thanks for reporting this @utof & @PrajwalPrashanth for the prompt PR! I have left r minot comment over the PR. This should get merged soon.
